WINDOW_WIDTH = 1024
WINDOW_HEIGHT = 720

GAME_NAME = "Asteroid Crush"
DEVELOPER = "Lakshya Pachkhede"
VERSION = "0.1"

GAME_STATE_MENU = 0
GAME_STATE_OVER = 1
GAME_STATE_LOOP = 2

CELL_W = 120
CELL_H = 120
